services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: doggishop-app
    container_name: laravel-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - networkapp

  db:
    image: mysql:8.0
    container_name: laravel-docker
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - networkapp

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - networkapp

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: 2ntgze8S527kQseRtvTnEZjk3VQ_wHALeyyBh5osq8jhqjNQ
    ports:
      - 4040:4040
networks:
  networkapp:
    driver: bridge